### ISSUE TITLE
Add missing icons

### ISSUE THREAD

**Issue by pilhuhn** [pilhuhn/ZwitscherA#36]
New tweet button is too small, 
A search tab + search button is needed
Add user button

**Comment by wwerner** [comment]
It seems like all the bubble icons are 32x28.
Is there something different w/ the post icon?

Working on the other issues.

Btw., I pushed the source files to https://github.com/wwerner/Zwitscher-Icons

**Comment by pilhuhn** [comment]
On the start screen the post button looks less high than the "to top" and "refresh" buttons the latter are 32x32, which I think is the right size here (square)

**Comment by wwerner** [comment]
Search tab icon is pushed: 21727e19a4ad51a45061

**Comment by pilhuhn** [comment]
Follow / unfollow user could use an icon too.

Geo? Checkbox as well.

**Comment by pilhuhn** [comment]
Send-off button is also needed for the NewTweetActivity.

**Comment by wwerner** [comment]
Pushed button size fixes and search buttons: f12b2623530940b8bca9 .
Also switched active/inactive tab buttons: 5c31d272e2c7f6734573 , a74d9ef975f930e760d1 .
