### ISSUE TITLE
hardcoded filepath of twitter4j-core-2.1.4.jar

### ISSUE THREAD

**Issue by printminion** [pilhuhn/ZwitscherA#4]
File .classpath
ACTUAL:
&lt;classpathentry kind="lib" path="/devel/ZwitscherA/libs/twitter4j-core-2.1.4.jar"/&gt;

SHALL:
  &lt;classpathentry kind="lib" path="libs/twitter4j-core-2.1.4.jar" /&gt;

**Comment by pilhuhn** [comment]
Make entry for t4j relative. Closed by 0b684c0f2e7ccfc95e7b75ed75ae7a2e80ba6b83
