### ISSUE TITLE
back button "endless loop" instead of returning to previous activity/home screen

### ISSUE THREAD

**Issue by gregnotcraig** [pilhuhn/ZwitscherA#47]
when using the hardware back button, as expected, the app goes to previous screens (normal android behavior - killing process and returning to previous activity). what would be expected is that at some point pressing the back button would bring you to the home screen, or the previous application, but zwitcher goes in to a loop and keeps on the account home timeline.

**Comment by pilhuhn** [comment]
As said before, I think the behavior of staying in the app and only leaving the app when pressing Home is my preferred way of doing this.

Having said this, I understand that Android is here different from iOS and that users expect the hardware back button (which does not exist in iOS) to bring them back to the launchers

**Comment by pilhuhn** [comment]
Finish this activity in proceed() so that the back button allows to get out of the app. Closed by 0d9dc307184e3478d1db70fcab7dacdd163ac278.
