### ISSUE TITLE
url shortening service for identi.ca

### ISSUE THREAD

**Issue by kmacphail** [pilhuhn/ZwitscherA#58]
Whilst I am aware that this is primarily a Twitter based client and that all the features are available on identi.ca currently, I do feel that a url shortening service would improve it's integration with identi.ca significantly.  140 characters isn't a lot and when putting in a full url this can often take the user well over the limit.

**Comment by pilhuhn** [comment]
I like this idea.
How do you see semantics here? Type longer text and have urls shortened when sending? I think with shorteners like bit.ly the final length is known in advance? Or have a button to do "online shortening"?

Also as I want to support full offline mote at some point in the (hopefully not too far future), shortening would only possible when sending and an internet connection is available again.

And, as side note, I do intent to better support identi.ca and general status.net instances.

**Comment by kmacphail** [comment]
I would suggest that it is done similar to the form Mustard currently uses, when you are composing a message there is a "shorten URL" button that automatically shortens the url entered into the message (I think it uses b1t.it ).  This method also allows the user know how many characters are used up before the message is dent.

**Comment by pilhuhn** [comment]
But still - what about offline mode?
