### ISSUE TITLE
progress/loader bar needed

### ISSUE THREAD

**Issue by printminion** [pilhuhn/ZwitscherA#7]
Some kind of progress bar needed.
I have no idea if there some activities on background or informations exchange with twitter

**Comment by pilhuhn** [comment]
I was trying to do this yesterday, but had no luck so far. Need to investigate again.

**Comment by pilhuhn** [comment]
This is less than trivial as needs certain order of things see http://javablogs.com/Jump.action?id=611394

**Comment by pilhuhn** [comment]
Add progress indicator in the right side of the window title bar.  Closed by 5fd4e9718542580403884807e02d236aee109c05
