### ISSUE TITLE
UI: Better solution for lists

### ISSUE THREAD

**Issue by printminion** [pilhuhn/ZwitscherA#8]
Maximum amount of lists in twitter is 20 ;)

I have 13 http://img811.imageshack.us/img811/5475/deviceb.png

**Comment by pilhuhn** [comment]
What about having tabs for home, mention, list, direct, search
and then below direct, list, direct, search a ListView each with the title of e.g. the list (perhpaps with decorator for number of unread) where clicking on the list entry leads to the individual list / saved search / ...

This is one click more for lists than for home, which I don't really consider first class citizen anymore, but would allow to have more than 20 lists (and larger titles on the tabs with many lists).

**Comment by pilhuhn** [comment]
Ah I see, more than 20 lists are not possible by Twitter.
Anyway commit 69cbbe6 changes behavior to one top level "lists" tab which lists all lists and then the individual lists hanging on this.

**Comment by pilhuhn** [comment]
Forgot to implement list reloading :-(

**Comment by pilhuhn** [comment]
Implement reload button on lists (and a disabled post button for now). Closed by b7da11936dc4665600f9b88d6495c08c690a1e6d
