### ISSUE TITLE
Cannot authorize account

### ISSUE THREAD

**Issue by dalb8** [pilhuhn/ZwitscherA#81]
I downloaded the most recent apk from github v0.84  and when it redirects to twitter.com for authorization , Twitter says "something has gone awry". I authorized an app this morning so I don't think it's problem on my end.

**Comment by dalb8** [comment]
I didnt realise I had to put the password into the app. It looks like twitter but it would be better to be sent to twitter.com in the browser.

**Comment by pilhuhn** [comment]
Hey,
thanks for your feedback. This is clearly a weak spot right now.
On the login page you have two options:
login directly with username and password - That works if the app was authorized before.
Or use the "login with twitter OAuth" button which sends you to twitter and allows to authorize.

I need to fix that - but am not exactly sure yet how, as identi.ca works more like classic twitter.

Thanks
  Heiko

**Comment by dalb8** [comment]
"Heiko W. Rupp" reply@reply.github.com a écrit :

> Hey,
> thanks for your feedback. This is clearly a weak spot right now.
> On the login page you have two options:
> login directly with username and password - That works if the app was
> authorized before.
> Or use the "login with twitter OAuth" button which sends you to twitter
> and allows to authorize.
> 
> I need to fix that - but am not exactly sure yet how, as identi.ca
> works more like classic twitter.
> 
> Thanks
>  Heiko
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pilhuhn/ZwitscherA/issues/81#issuecomment-6080385

I don't see it as a bug, but a flaw of the oauth system, I can't check the SSL certificates or anything in that window where I would put my password.

**Comment by dalb8** [comment]
identi.ca uses oauth now.
